---
- name: "Update package sources"
  apt:
    update_cache: yes
  become: true

- name: "Install os packages"
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - vim
      - xz-utils
    state: latest
  become: true